global map_name_list, map_abbr_list
map_name_list = [
    "Scuttlesink Marsh",
    "Everwinter Incline",
    "Timbertop Escarp",
    "Timberslope Bridge",
    "Swiftsands Chaparral",
    "Greenshore Bay",
    "Meltwater Channel",
    "Drownfield Sink",
    "Glacierfall Pass",
    "Whitepeak Tundra",
    "Stonemouth Southbluff",
    "Whitewall Pass",
    "Thunderrock Draw",
    "Flammog Desolation",
    "Glacierfall Fissure",
    "Sandmount Ascent",
    "Deathreach Priory",
    "Highstone Loch",
    "Redtree Enclave",
    "Sunkenbough Spring",
    "Darkbough Snag",
    "Rivercopse Fount",
    "Sunfang Dawn",
    "Parchsand Drought",
    "Murdergulch Divide",
    "Murdergulch Ravine",
    "Razorrock Gulch",
    "Avalanche Incline",
    "Whitebank Ridge",
    "Deepwood Pines",
    "Floatshoal Bight",
    "Meltwater Sump",
    "Shaleheath Steep",
    "Everwinter Passage",
    "Everwinter Expanse",
    "Timbertop Wood",
    "Wetgrave Swale",
    "Wetgrave Marsh",
    "Timberslope Grove",
    "Swiftsands Basin",
    "Skullmarsh Upper",
    "Giantweald Edge",
    "Drybasin Oasis",
    "Slakesands Mesa",
    "Munten Fell",
    "Hightree Isle",
    "Hightree Hillock",
    "Willowshade Hills",
    "Timberscar Copse",
    "Drownfield Quag",
    "Skysand Ridge",
    "Everwinter Gap",
    "Glacierfall Cross",
    "Glacierfall Valley",
    "Whitepeak Spring",
    "Springsump Melt",
    "Southgrove Thicket",
    "Sunstrand Quicksands",
    "Frostspring Volcano",
    "Whitewall Ridge",
    "Runnelvein Sink",
    "Deepwood Copse",
    "Giantweald Glade",
    "Skylake Hinterlands",
    "Iceburn Cliffs",
    "Iceburn Tundra",
    "Willowshade Sink",
    "Widemoor Fen",
    "Twinchannel Narrows",
    "Westweald Shore",
    "Sandmount Desert",
    "Sandrift Dunes",
    "Farshore Drylands",
    "Sandrift Fringe",
    "Farshore Cape",
    "Highstone Mound",
    "Frostseep Crevasse",
    "Longfen Veins",
    "Greenhollow Copse",
    "Battlebrae Meadow",
    "Windgrass Terrace",
    "Gravemound Knoll",
    "Gravemound Cliffs",
    "Deathwisp Sink",
    "Deathwisp Bog",
    "Sunkenbough Woods",
    "Rivercopse Curve",
    "Driftwood Hollow",
    "Rivercopse Path",
    "Sunfang Cliffs",
    "Sunfang Wasteland",
    "Thunderrock Ascent",
    "Thunderrock Upland",
    "Murdergulch Trail",
    "Razorrock Chasm",
    "Razorrock Verge",
    "Razorrock Bank",
    "Highstone Plateau",
    "Battlebrae Grassland",
    "Firesink Trench",
    "Whitecliff Expanse",
    "Dryvein End",
    "Thirstwater Gully",
    "Dryvein Confluence",
    "Northstrand Beach",
    "Scuttlesink Mouth",
    "Whitebank Wall",
    "Timberslope Dell",
    "Frostpeak Ascent",
    "Floatshoal Fissure",
    "Meltwater Delta",
    "Everwinter Plain",
    "Everwinter Gorge",
    "Everwinter Peak",
    "Timbertop Dale",
    "Shaleheath Hills",
    "Skylake Bridge",
    "Giantweald Woods",
    "Watchwood Lakeside",
    "Watchwood Bluffs",
    "Flatrock Plateau",
    "Munten Tundra",
    "Hightree Pass",
    "Hightree Levee",
    "Hightree Cliffs",
    "Glacierbreak Summit",
    "Widemoor Hills",
    "Drownfield Wetland",
    "Widemoor End",
    "Willowshade Pools",
    "Widemoor Woods",
    "Drytop Riverbed",
    "Drytop Pillars",
    "Drownfield Slough",
    "Drownfield Rut",
    "Glacierfall Canyon",
    "Springsump Wetland",
    "Southgrove Copse",
    "Dryvein Oasis",
    "Sunstrand Dunes",
    "Farshore Heath",
    "Stonelake Hillock",
    "Frostspring Passage",
    "Runnelvein Bog",
    "Deepwood Gorge",
    "Giantweald Roots",
    "Iceburn Peaks",
    "Flammog Valley",
    "Widemoor Flats",
    "Driftwood Glen",
    "Bleachskull Desert",
    "Sandrift Expanse",
    "Farshore Lagoon",
    "Braemore Lowland",
    "Windgrass Fields",
    "Windgrass Coast",
    "Frostbite Mountain",
    "Mudfoot Mounds",
    "Gravemound Slope",
    "Hightree Borderlands",
    "Sunfang Approach",
    "Parchsand Cliffs",
    "Thunderrock Rapids",
    "Razorrock Ravine",
    "Razorrock Edge",
    "Stonemouth Bay",
    "Firesink Caldera",
    "Whitecliff Peak",
    "Longfen Arms",
    "Thirstwater Waste",
    "Dryvein Steppe",
    "Northstrand Dunes",
    "Deepwood Dell",
    "Whitebank Stream",
    "Whitebank Shore",
    "Whitebank Cross",
    "Meltwater Bog",
    "Whitebank Descent",
    "Frostpeak Vista",
    "Skysand Plateau",
    "Everwinter Crossing",
    "Brambleshore Hinterlands",
    "Everwinter Reach",
    "Scuttlesink Pools",
    "Everwinter Shores",
    "Wetgrave Bog",
    "Swiftsands Plain",
    "Drybasin Riverbed",
    "Flatrock Cliffs",
    "Skullmarsh Lower",
    "Greenshore Peninsula",
    "Giantweald Dale",
    "Watchwood Precipice",
    "Watchwood Grove",
    "Slakesands Canyon",
    "Munten Rise",
    "Hightree Steep",
    "Hightree Lake",
    "Hightree Dale",
    "Hightree Strand",
    "Hightree Glade",
    "Hightree Enclave",
    "Drownfield Course",
    "Widemoor Shore",
    "Widemoor Pool",
    "Willowshade Wetlands",
    "Widemoor Estuary",
    "Timberscar Dell",
    "Drownfield Mire",
    "Drownfield Fen",
    "Deadpine Forest",
    "Glacierfall Passage",
    "Whitepeak Ascent",
    "Springsump Basin",
    "Southgrove Escarp",
    "Dryvein Cross",
    "Sunstrand Shoal",
    "Sunstrand Delta",
    "Dryvein Plain",
    "Farshore Esker",
    "Battlebrae Peaks",
    "Stonelake Fields",
    "Runnelvein Slough",
    "Giantweald Copse",
    "Floatshoal Floe",
    "Iceburn Firth",
    "Flammog Fork",
    "Widemoor Delta",
    "Willowshade Mire",
    "Willowshade Lake",
    "Willowshade Icemarsh",
    "Westweald Thicket",
    "Sandmount Strand",
    "Bleachskull Steppe",
    "Sandmount Esker",
    "Sandrift Steppe",
    "Sandrift Prairie",
    "Sandrift Coast",
    "Sandrift Shore",
    "Farshore Bay",
    "Braemore Upland",
    "Windgrass Border",
    "Windgrass Gully",
    "Windgrass Rill",
    "Windgrass Precipice",
    "Avalanche Ravine",
    "Frostbite Chasm",
    "Frostseep Ravine",
    "Longfen Marsh",
    "Mudfoot Sump",
    "Greenhollow Vale",
    "Highstone Plains",
    "Battlebrae Flatland",
    "Highstone Grassland",
    "Gravemound Brim",
    "Gravemound Hills",
    "Rivercopse Crossing",
    "Driftwood Vale",
    "Sunfang Ravine",
    "Murdergulch Cross",
    "Murdergulch Gap",
    "Razorrock Passage",
    "Razorrock Valley",
    "Highstone Meadow",
    "Battlebrae Plain",
    "Battlebrae Lake",
    "Stonemouth Northbluff",
    "Thirstwater Steppe",
    "Drybasin Riverbed"
]

map_abbr_list = [
    "SM",
    "EI",
    "TE",
    "TB",
    "SC",
    "GB",
    "MC",
    "DS",
    "GP",
    "WT",
    "SS",
    "WP",
    "TD",
    "FD",
    "GF",
    "SA",
    "DP",
    "HL",
    "RE",
    "SS",
    "DS",
    "RF",
    "SD",
    "PD",
    "MD",
    "MR",
    "RG",
    "AI",
    "WR",
    "DP",
    "FB",
    "MS",
    "SS",
    "EP",
    "EE",
    "TW",
    "WS",
    "WM",
    "TG",
    "SB",
    "SU",
    "GE",
    "DO",
    "SM",
    "MF",
    "HI",
    "HH",
    "WH",
    "TC",
    "DQ",
    "SR",
    "EG",
    "GC",
    "GV",
    "WS",
    "SM",
    "ST",
    "SQ",
    "FV",
    "WR",
    "RS",
    "DC",
    "GG",
    "SH",
    "IC",
    "IT",
    "WS",
    "WF",
    "TN",
    "WS",
    "SD",
    "SD",
    "FD",
    "SF",
    "FC",
    "HM",
    "FC",
    "LV",
    "GC",
    "BM",
    "WT",
    "GK",
    "GC",
    "DS",
    "DB",
    "SW",
    "RC",
    "DH",
    "RP",
    "SC",
    "SW",
    "TA",
    "TU",
    "MT",
    "RC",
    "RV",
    "RB",
    "HP",
    "BG",
    "FT",
    "WE",
    "DE",
    "TG",
    "DC",
    "NB",
    "SM",
    "WW",
    "TD",
    "FA",
    "FF",
    "MD",
    "EP",
    "EG",
    "EP",
    "TD",
    "SH",
    "SB",
    "GW",
    "WL",
    "WB",
    "FP",
    "MT",
    "HP",
    "HL",
    "HC",
    "GS",
    "WH",
    "DW",
    "WE",
    "WP",
    "WW",
    "DR",
    "DP",
    "DS",
    "DR",
    "GC",
    "SW",
    "SC",
    "DO",
    "SD",
    "FH",
    "SH",
    "FP",
    "RB",
    "DG",
    "GR",
    "IP",
    "FV",
    "WF",
    "DG",
    "BD",
    "SE",
    "FL",
    "BL",
    "WF",
    "WC",
    "FM",
    "MM",
    "GS",
    "HB",
    "SA",
    "PC",
    "TR",
    "RR",
    "RE",
    "SB",
    "FC",
    "WP",
    "LA",
    "TW",
    "DS",
    "ND",
    "DD",
    "WS",
    "WS",
    "WC",
    "MB",
    "WD",
    "FV",
    "SP",
    "EC",
    "BH",
    "ER",
    "SP",
    "ES",
    "WB",
    "SP",
    "DR",
    "FC",
    "SL",
    "GP",
    "GD",
    "WP",
    "WG",
    "SC",
    "MR",
    "HS",
    "HL",
    "HD",
    "HS",
    "HG",
    "HE",
    "DC",
    "WS",
    "WP",
    "WW",
    "WE",
    "TD",
    "DM",
    "DF",
    "DF",
    "GP",
    "WA",
    "SB",
    "SE",
    "DC",
    "SS",
    "SD",
    "DP",
    "FE",
    "BP",
    "SF",
    "RS",
    "GC",
    "FF",
    "IF",
    "FF",
    "WD",
    "WM",
    "WL",
    "WI",
    "WT",
    "SS",
    "BS",
    "SE",
    "SS",
    "SP",
    "SC",
    "SS",
    "FB",
    "BU",
    "WB",
    "WG",
    "WR",
    "WP",
    "AR",
    "FC",
    "FR",
    "LM",
    "MS",
    "GV",
    "HP",
    "BF",
    "HG",
    "GB",
    "GH",
    "RC",
    "DV",
    "SR",
    "MC",
    "MG",
    "RP",
    "RV",
    "HM",
    "BP",
    "BL",
    "SN",
    "TS",
    "DR"
]
map_name_list = sorted(map_name_list, key=str.lower) # 字母表顺序排列